# Generated by Django 4.1.5 on 2023-06-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('doj', models.DateField()),
                ('location', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Delhi', 'Delhi'), ('Bangalore', 'Bangalore')], max_length=25)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
